---
title: "Bonobo_steepness"
author: "Lucas Spicher"
date: "2025-01-13"
output: html_document
---
##Pan paniscus


1) De vries et al., 2006: 1 matrix of 7 bonobos but without infomartions in the paper
3) Furuichi 1997: it's all on the paper (sex & age)
4) Paoli & Palagi 2008: 2 matrices but no access to the paper
5) Surbeck et Hohmann 2013: 1 matrix and it's all on the paper (sex & age)
6) Vervaecke et al., 2000: 1 matrix and it's all on the paper (sex & age)

```{r}
library(EloSteepness.data)
library(EloSteepness)
library(EloRating)
```

# For the Surbeck 2013
bono6males<-c("ca","ti","ja","da","be")
bono6females<-c("ha","ri","ma","ev","ir","pa","zo","ol","gw","su")
bono6_malehierarchy<-empirical_raw_data$surbeck2013_dom_1[rownames(empirical_raw_data$surbeck2013_dom_1) %in% bono6males,colnames(empirical_raw_data$surbeck2013_dom_1) %in% bono6males]
bono6_femalehierarchy<-empirical_raw_data$surbeck2013_dom_1[rownames(empirical_raw_data$surbeck2013_dom_1) %in% bono6females,colnames(empirical_raw_data$surbeck2013_dom_1) %in% bono6females]


# The number of randomizations is set in the following way, unless a specific number is provided. If there are more than 500 observed interactions, n_rand = 5. If there are less than 100 interactions, n_rand = 50. In the remaining cases, n_rand = 20.
steep_bono6_males <- elo_steepness_from_matrix(mat = bono6_malehierarchy, 
                                         n_rand = case_when(sum(bono6_malehierarchy)>0 ~ 20,sum(bono6_malehierarchy)>500 ~ 5,sum(bono6_malehierarchy)<100 ~ 50  ), 
                                         refresh = 0, 
                                         cores = 2, 
                                         iter = 2000, 
                                         seed = 1)

steepness_bono6_males <-median(steep_bono6_males$steepness)


steep_bono6_females <- elo_steepness_from_matrix(mat = bono6_femalehierarchy, 
                                         n_rand = case_when(sum(bono6_femalehierarchy)>0 ~ 20,sum(bono6_femalehierarchy)>500 ~ 5,sum(bono6_femalehierarchy)<100 ~ 50  ), 
                                         refresh = 0, 
                                         cores = 2, 
                                         iter = 2000, 
                                         seed = 1)

steepness_bono6_females <-median(steep_bono6_females$steepness)

```
